@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

'left to right direction

class SystemAdministrator {
    - name
    - email
}

class CSVImport{
    + importData()
}

class ImportController {
    - AnnouncementRepository
    + importData()
    + checkFile()
}

class ImportUI {
    - ImportController
    + selectFile()
}

class AnnouncementRepository {
    - addAnnouncementFromImportedFile()
}

interface DataImporter{
    + importData()
}


ImportUI ..> ImportController : calls

'ImportInformationController --> LegacySystem : uses

SystemAdministrator -- ImportUI : interacts

ImportController ..> AnnouncementRepository : uses

ImportController ..> CSVImport : instantiates

CSVImport ..> DataImporter : implements

@enduml
