@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "System Administrator" as Admin
participant ":ImportUI" as UI
participant ":ImportController" as CTRL
participant "repositories\n:Repositories" as REPO
'participant ":Property" as PROP
'participant ":Address" as ADDR
'participant ":Order" as ORD
'participant ":Residency" as RES
'participant ":SunExposure" as SUN
participant ":CSVImport" as CSV
participant ":properties\n:Properties" as PROP
participant ":legacySystemFile\n:LegacySystemFile" as LEGACY
participant ":AnnouncementRepository" as ANNREPO
participant ":Announcement" as ANN


    activate Admin

    Admin -> UI : asks to import a csv file
    activate UI

    UI -> CTRL: getInstance()
    activate CTRL

'    CTRL -> UI : importController
'    activate REPO

'    UI -> CTRL : selectFile()
'    activate CTRL

    CTRL --> UI : selectFile()
    deactivate CTRL

    UI --> Admin : asks for csv file location
    deactivate UI

    Admin -> UI : provides file location
    activate UI

    UI -> CTRL : checkFile()
    activate CTRL

    CTRL -> REPO : getInstance()
    activate REPO

    REPO --> CTRL: repositories
    deactivate REPO

    CTRL -> REPO : getAnnouncementRepository()
    activate REPO

    REPO -> ANNREPO : getAnnouncementRepository()
    activate ANNREPO

    ANNREPO --> REPO: announcementRepository
    deactivate ANNREPO

    REPO --> CTRL: announcementRepository
    deactivate REPO

'    CTRL --> ANNREPO: importData()
'    activate ANNREPO

    CTRL --> PROP: importData()
    activate PROP

    PROP -> LEGACY: gets import Class
    activate LEGACY

    LEGACY --> PROP: returns import Class
    deactivate LEGACY

    PROP -> ANNREPO: imports Data based on import class
    activate ANNREPO

    ANNREPO --> ANN: creates new Announcement
    activate ANN

    ANN --> ANNREPO: returns new Announcement
    deactivate ANN

    ANNREPO --> PROP: returns importResult
    deactivate ANNREPO

    PROP --> CTRL: returns importResult
    deactivate PROP

    CTRL -> UI : displayImportResult(importResult)
    deactivate CTRL

    UI --> Admin : displays success message or error
    deactivate UI

@enduml
