@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "System Administrator" as Admin
participant ":ImportUI" as UI
participant ":ImportController" as CTRL
participant "repositories\n:Repositories" as REPO
participant ":AnnouncementRepository" as ANNREPO
participant ":Announcement" as ANN
participant ":Property" as PROP
participant ":Address" as ADDR
participant ":Order" as ORD
participant ":Residency" as RES
participant ":SunExposure" as SUN


    activate Admin

    Admin -> UI : asks to import a csv file
    activate UI

    UI -> CTRL: getInstance()
    activate CTRL

'    CTRL -> UI : importController
'    activate REPO

'    UI -> CTRL : selectFile()
'    activate CTRL

    CTRL --> UI : selectFile()
    deactivate CTRL

    UI --> Admin : asks for csv file location
    deactivate UI

    Admin -> UI : provides file location
    activate UI

    UI -> CTRL : checkFile()
    activate CTRL

    CTRL -> REPO : getInstance()
    activate REPO

    REPO --> CTRL: repositories
    deactivate REPO

    CTRL -> REPO : getAnnouncementRepository()
    activate REPO

    REPO -> ANNREPO : getAuthenticationRepository()
    activate ANNREPO

    ANNREPO --> REPO: authenticationRepository
    deactivate ANNREPO

    REPO --> CTRL: announcementRepository
    deactivate REPO

    CTRL --> ANNREPO: addAnnouncementFromImportedFile()
    activate ANNREPO

    ANNREPO -> CTRL : returns importResult
    deactivate ANNREPO

    CTRL -> UI : displayImportResult(importResult)
    deactivate CTRL

    UI --> Admin : displays success message or error
    deactivate UI

@enduml
