@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Agent" as AGENT
participant ":PublishSaleAnnouncementUI" as UI
participant ":PublishAnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REPO
participant "saleAnnouncementRepository:\nSaleAnnouncementRepository" as SaleAnnouncementRepository
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant "Announcement" as ANN

activate AGENT

AGENT -> UI : asks to publish an announcement

activate UI

    UI -> CTRL : publishAnnouncement(announcement)
    activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> REPO : getSaleAnnouncementRepository()
        activate REPO

            REPO --> CTRL: saleAnnouncementRepository
        deactivate REPO

        CTRL -> SaleAnnouncementRepository : updateAnnouncement(announcement)
        activate SaleAnnouncementRepository

            SaleAnnouncementRepository --> CTRL : updatedAnnouncement
        deactivate SaleAnnouncementRepository

        CTRL -> CTRL : getAgentFromSession()
        activate CTRL

            CTRL -> _APP: getInstance()
            activate _APP
                _APP -> CTRL: appSession
            deactivate _APP

            CTRL -> APP: getCurrentSession()
            activate APP

                APP --> CTRL: currentSession
            deactivate APP

            CTRL -> SESSION: email = getUserEmail()
            activate SESSION

                SESSION --> CTRL: email
            deactivate SESSION

        CTRL --> UI : updatedAnnouncement

    deactivate CTRL

    UI --> AGENT : shows updated announcement
deactivate UI

AGENT -> UI : confirms publication
activate UI

    UI -> CTRL : publishAnnouncement(announcement)
    activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> REPO : getSaleAnnouncementRepository()
        activate REPO

            REPO --> CTRL: saleAnnouncementRepository
        deactivate REPO

        CTRL -> SaleAnnouncementRepository : updateAnnouncement(announcement)
        activate SaleAnnouncementRepository

            SaleAnnouncementRepository --> CTRL : updatedAnnouncement
        deactivate SaleAnnouncementRepository

        CTRL -> CTRL : getAgentFromSession()
        activate CTRL

            CTRL -> _APP: getInstance()
            activate _APP
                _APP -> CTRL: appSession
            deactivate _APP

            CTRL -> APP: getCurrentSession()
            activate APP

                APP --> CTRL: currentSession
            deactivate APP

            CTRL -> SESSION: email = getUserEmail()
            activate SESSION

                SESSION --> CTRL: email
            deactivate SESSION

        CTRL --> UI : updatedAnnouncement

    deactivate CTRL

    UI --> AGENT : shows updated announcement
deactivate UI

AGENT -> UI : closes UI
deactivate AGENT
deactivate UI
@enduml
