@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Unregistered User" as User
participant ":System" as System

activate User

    User -> System : Asks to list properties
    activate System

    System --> User : Shows filter and sort options
    deactivate System

    alt Choose options

        opt Filter
            User -> System : selects filters and asks to list properties (type of business, type of property, number of rooms)
            activate System

            System --> User : shows filtered properties
            deactivate System
        end

        opt Sort
            User -> System : selects criteria to sort options and ask to list properties (price, state)
            activate System

            System --> User : shows properties orderes by the selected criteria
            deactivate System
        end

    end

    alt No options chosen
        User -> System : asks to list properties (without filters and sort)
        activate System

        System --> User : shows properties ordered by default criteria (most recently added)
        deactivate System
    end

@enduml