@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Unregistered User" as User
participant ":System" as System

activate User

    User -> System : Asks to list properties
    activate System

    System --> User : Shows filter and sort options
    deactivate System

    alt Choose both options
        User -> System : selects filters and asks to list properties (type of business, type of property, number of rooms)
        activate System

        System --> User : shows filtered properties
        deactivate System

        User -> System : selects criteria to sort options and asks to list properties (price, state)
        activate System

        System --> User : shows the previously filtered properties sorted by the selected criteria
        deactivate System
    end
    alt Choose only one option

        alt Filter
            User -> System : selects filters and asks to list properties (type of business, type of property, number of rooms)
            activate System

            System --> User : shows filtered properties
            deactivate System
        end

        alt Sort
            User -> System : selects criteria to sort options and ask to list properties (price, state)
            activate System

            System --> User : shows properties sorted by the selected criteria
            deactivate System
        end

    end

    alt Choose no options
        User -> System : asks to list properties (without filters and sort)
        activate System

        System --> User : shows all properties sorted by default criteria (most recently added)
        deactivate System
    end

@enduml