@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Unregistered User" as User
participant ":System" as System

activate User

    User -> System : requests to list properties
    activate System

    System --> User : shows property filter and sort options and requests user to choose
    deactivate System

    alt Filter and Sort
        User -> System : selects filter options (type of business, type of property, number of rooms)
        activate System

        User -> System : selects criteria to sort (price, state) and chooses order (ascending or descending)
        System --> User : shows filter and sort options selected by user and requests confirmation
        deactivate System

    else Filter or Sort

        alt Filter
            User -> System : selects filter options (type of business, type of property, number of rooms)
            activate System

            System --> User : shows filter options selected by user, default sort criteria (most recently added) and requests confirmation
            deactivate System

        else Sort
            User -> System : selects criteria to sort (price, state) and chooses order (ascending or descending)
            activate System

            System --> User : shows that all properties will be listed with sort criteria selected by user and requests confirmation
            deactivate System
        end


    else Neither Filter nor Sort
        User -> System : requests to list properties (without selecting filter and sort criteria)
        activate System

        System --> User : shows that all properties will be listed with default sort criteria (most recently added) and requests confirmation
        deactivate System

    end

    User -> System : confirms selection
    activate System

    System --> User : displays the respective list of properties
    deactivate System




@enduml