@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model of US016

class Agent {
}

class VisitSchedule{
    name
    telephoneNumber
    date
    startTime
    endTime
    aprovatedByAgent
    agentEmail
    adressOfProperty
    requesterEmail
}
Agent "*" -- "*" VisitSchedule : confirm/reject >

@enduml