@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
'skinparam linetype ortho
hide circle
hide methods

title Domain Model

class Client{
    name
    passportCardNumber
    taxNumber
    email
    telephoneNumber
}

class Owner {
}

class Employee{
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class Agent{
    agency
}

'class Property{
'    typeOfProperty
'    area
'    location
'    distanceFromCityCentre
'    requestedPrice
'    photographs
'    numberOfBedrooms
'    numberOfBathrooms
'    numberOfParkingSpaces
'    availableEquipment
'    hasBasement
'    hasInhabitableLoft
'    sunExposureValue
'}

class Property extends Address{
    typeOfBusiness
    typeOfProperty
    area
    distanceFromCenter
    price
}

class Photos {
}

class Address{
    street
    doorNumber
    zipCode
}

class City{
}

class District{
}

class State{
}

class Apartment extends Residency{
}

class House extends Residency{
    basement
    inhabitableLoft
    sunExposure
}

class Residency extends Property{
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces

}

class PublishedProperty{
    publishedDate
    publishedBy
    commission
}

class Commission{
    percentage
    value
}

class Land extends Property{
}

class Equipment{
    equipmentName
}

class Role{
}

class SystemAdministrator{
}

class StoreManager{
}

class StoreNetworkManager{
}


Agent "1" -- "1" Employee: is a <
Employee "1" -- "1" Role: has a role of >
SystemAdministrator "1" -- "1" Role: has a role of >
StoreNetworkManager "1" -- "1" Role: has a role of >
SystemAdministrator "1" -- "1" Role: has a role of >
SystemAdministrator "1" -- "1" Employee: is a >
Agent "1" -- "1" Owner : contacted by
Agent "*" - "*" Property: publishes
Agent "1" - "*" Property: sets commission
Owner "1" - "*" Property: owns <
Address "1" -- "1" City : is a part of <
City "1" -- "1" District : is a part of <
District "1" -- "1" State : is a part of <
Client "1" -- "*" Address: has >
Property "1" -- "*" Photos: has >
PublishedProperty "1" -- "1" Commission: is set for <
House "1" -- "*" Equipment: has >
Apartment "1" -- "*" Equipment: has >
PublishedProperty "1" -- "1" Property: is a part of <

'Property <|-- House
'Property <|-- Apartment
'Property <|-- Land
@enduml
