@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Owner {
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class Agency{
    designation
    location
    emailAddress
    telephoneNumber
    }

class Agent {
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class Resident{
    typeOfBusiness
    typeOfProperty
     area
     location
     distanceFromCenter
      price
}
class House{
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces
    availableEquipment
    basement
    inhabitableLoft
    sunExposure
}

class Apartment{
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces
    availableEquipment
}

class House{
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces
    availableEquipment
    basement
    inhabitableLoft
    sunExposure
}

class Land{

}
class RentalAgreement{
    rentalDuration
}
Owner "1" - "1" Agency : Select >
Owner "1" - "0..*" Property: submit >
Owner "1" -- "1" Agent:assign >
Agent "1" - "0..*" Property
Property "1"-"1" RentalAgreement
Property "1"-"1" Resident
Owner "1" -"1" RentalAgreement:define >
Property <|-- House
Property <|-- Apartment
Property <|-- Land
@enduml