@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : Tells System that they received a call with a property for sale
    activate System

    System --> Agent : requests data
    deactivate System

    Agent -> System : types requested data (dimensions, description, \nvalue, cost)
    activate System

    System --> Agent : displays operation success; Asks to set the commission
    deactivate System

@enduml