@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Owner" as Owner
actor "Agent" as Agent
participant ":System" as System

activate Agent

    Owner -> Agent : Calls the Agent with a property for sale
    activate System

    Agent --> System : Tells System that they received \na call with a property for sale

    System --> Agent : requests data
    deactivate System

    Agent -> System : types requested data (dimensions, description, \nvalue, cost)
    activate System

    System --> Agent : displays operation success
    deactivate System

@enduml