@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Unregistered User" as uUser
participant ":ListAnnouncementsUI" as UI
participant ":ListPropertiesController" as CTRL
participant ":Repositories" as REPOS
participant "repositories\n:Repositories" as repos
participant "announcementsRepository:\nAnnouncementsRepository" as AnnouncementsRepository

activate uUser

            uUser -> UI : requests to list properties
            activate UI
            deactivate UI

            alt Filter and Sort
                UI --> uUser : shows type of property options (House, Apartement or Land) and requests user to choose
                activate UI
                deactivate UI

                uUser -> UI : selects type of property
                activate UI

                UI --> uUser : shows type of business options (Sale or Rent) and requests user to choose
                deactivate UI

                uUser -> UI : selects type of business
                activate UI

                UI --> uUser : shows number of rooms options (1, 2, 3, 4 or 5) filter and requests user to choose
                deactivate UI

                uUser -> UI : selects number of rooms
                activate UI

                UI --> uUser : shows sort criterias (Price, City or State) and requests user to choose
                deactivate UI

                uUser -> UI : selects sort criteria
                activate UI

                UI --> uUser : shows order options (Ascending or Descending) and requests user to choose
                deactivate UI

                uUser -> UI : selects order
                activate UI

                UI --> uUser : shows filter and sort options selected by user and requests confirmation
                deactivate UI



            else Only Filter

                    UI --> uUser : shows filter and sort options
                    activate UI
                    deactivate UI

                    uUser -> UI : selects filter options but doesn't select sort options
                    activate UI

                    UI --> uUser: shows that properties will be filtered using filter options selected by user, \n sorted by default sort criteria (most recently added) and requests confirmation
                    deactivate UI

            else Only Sort

                    UI --> uUser : shows filter and sort options
                    activate UI
                    deactivate UI

                    uUser -> UI: selects sort options but doesn't select filter options
                    activate UI

                    UI --> uUser : shows that all properties will be listed with sort criteria selected by user
                    deactivate UI


            else Neither Filter nor Sort

                UI --> uUser : shows filter and sort options
                activate UI
                deactivate UI

                uUser -> UI : neither selects filter options nor sort options
                activate UI

                UI --> uUser : shows that all properties will be listed with default sort criteria (most recently added) and requests confirmation
                deactivate UI

            end

            uUser -> UI : confirms selection
            activate UI

            UI -> UI : checkInputType(typeOfProperty, transactionType, numberOfRooms, sortCriteria)

            UI -> CTRL** : create
            alt Filter and Sort
                UI -> CTRL : getFilteredAndSortedAnnouncements(typeOfProperty, transactionType, numberOfRooms, sortCriteria, order)

                activate CTRL

                CTRL -> REPOS : getInstance()
                activate REPOS

                REPOS --> CTRL: repositories
                deactivate REPOS

                CTRL -> repos : getAnnouncementRepository()
                activate repos

                repos --> CTRL: announcementsRepository
                deactivate repos

                CTRL -> AnnouncementsRepository : getFilteredAndSortedAnnouncements(propertyType, transactionType, numberOfRooms, sortCriteria, order)
                activate AnnouncementsRepository

                AnnouncementsRepository -> AnnouncementsRepository : getFilteredAndSortedAnnouncements(propertyType, transactionType, numberOfRooms, sortCriteria, order)

                AnnouncementsRepository --> CTRL : announcementsList
                deactivate AnnouncementsRepository

                CTRL --> UI : announcementsList

                deactivate CTRL


                deactivate UI
            else Only filter
                UI -> CTRL : getFilteredAnnouncements(typeOfProperty, transactionType, numberOfRooms)
                activate UI
                activate CTRL

                CTRL -> REPOS : getInstance()
                activate REPOS

                REPOS --> CTRL: repositories
                deactivate REPOS

                CTRL -> repos : getAnnouncementRepository()
                activate repos

                repos --> CTRL: announcementsRepository
                deactivate repos

                CTRL -> AnnouncementsRepository : getFilteredAnnouncements(propertyType, transactionType, numberOfRooms)
                activate AnnouncementsRepository

                AnnouncementsRepository -> AnnouncementsRepository : getFilteredAnnouncements(propertyType, transactionType, numberOfRooms)

                AnnouncementsRepository --> CTRL : announcementsList
                deactivate AnnouncementsRepository

                CTRL --> UI : announcementsList

                deactivate CTRL


                deactivate UI

            else Only sort
                UI -> CTRL : getAllAnnouncementsSortedBySortCriteria(sortCriteria, order)
                activate UI
                activate CTRL

                CTRL -> REPOS : getInstance()
                activate REPOS

                REPOS --> CTRL: repositories
                deactivate REPOS

                CTRL -> repos : getAnnouncementRepository()
                activate repos

                repos --> CTRL: announcementsRepository
                deactivate repos

                CTRL -> AnnouncementsRepository : getAllAnnouncementsSortedBySortCriteria(sortCriteria, order)
                activate AnnouncementsRepository

                AnnouncementsRepository -> AnnouncementsRepository : getAllAnnouncementsSortedBySortCriteria(sortCriteria, order)

                AnnouncementsRepository --> CTRL : announcementsList
                deactivate AnnouncementsRepository

                CTRL --> UI : announcementsList

                deactivate CTRL


                deactivate UI
            else Neither Filter nor Sort
                UI -> CTRL : getAllAnnouncementsSortedByDefualtCriteria()
                activate UI
                activate CTRL

                CTRL -> REPOS : getInstance()
                activate REPOS

                REPOS --> CTRL: repositories
                deactivate REPOS

                CTRL -> repos : getAnnouncementRepository()
                activate repos

                repos --> CTRL: announcementsRepository
                deactivate repos

                CTRL -> AnnouncementsRepository : getAllAnnouncementsSortedByDefualtCriteria()
                activate AnnouncementsRepository

                AnnouncementsRepository -> AnnouncementsRepository : getAllAnnouncementsSortedByDefualtCriteria()

                AnnouncementsRepository --> CTRL : announcementsList
                deactivate AnnouncementsRepository

                CTRL --> UI : announcementsList

                deactivate CTRL


                deactivate UI
            end


            UI -> UI : showAnnouncements(announcementsList)
            activate UI

            UI --> uUser : displays the respective list of properties
            deactivate UI



@enduml