@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Unregistered User" as uUser
participant ":ListPropertiesUI" as UI
participant ":ListPropertiesController" as CTRL
participant ":Repositories" as REPOS
participant "repositories\n:Repositories" as repos
participant "publishedPropertiesRepository:\nPublishedPropertiesRepository" as PublishedPropertiesRepository

activate uUser

            uUser -> UI : requests to list properties
            activate UI


            UI --> uUser : shows property filter and sort options and requests user to choose

            deactivate UI


            alt Filter and Sort

                uUser -> UI : selects filter option (type of business, type of property, number of rooms)
                activate UI

                uUser -> UI : selects criteria to sort (price, state)
                deactivate PublishedPropertiesRepository


                UI --> uUser : shows filter and sort options selected by user and requests confirmation
                deactivate UI

            else Filter or Sort

                alt Filter
                    uUser -> UI : selects filter option (type of business, type of property, number of rooms)
                    activate UI

                    UI --> uUser: shows filter option selected by user, default sort criteria (most recently added) and requests confirmation
                    deactivate UI

                else Sort
                    uUser -> UI: selects criteria to sort options and requests to list properties (price, state)
                    activate UI

                    UI --> uUser : shows that all properties will be listed with sort criteria selected by user and requests confirmation
                    deactivate UI
                end

            else Neither Filter nor Sort
                uUser -> UI : requests to list properties (without selecting filter and sort criteria)
                activate UI

                UI --> uUser : shows that all properties will be listed with default sort criteria (most recently added) and requests confirmation
                deactivate UI

            end

            uUser -> UI : confirms selection
            activate UI

            UI -> CTRL** : create
            UI -> CTRL : getPublishedProperties(propertyType, buisnessType, numberOfRooms, price, state)

            activate CTRL

            CTRL -> REPOS : getInstance()
            activate REPOS

            REPOS --> CTRL: repositories
            deactivate REPOS

            CTRL -> repos : getPublishedPropertiesRepository()
            activate repos

            repos --> CTRL: publishedPropertiesRepository
            deactivate repos

            CTRL -> PublishedPropertiesRepository : getPublishedProperties(propertyType, buisnessType, numberOfRooms, price, state)
            activate PublishedPropertiesRepository

            PublishedPropertiesRepository --> CTRL : requestedPublishedPropertiesList
            deactivate PublishedPropertiesRepository

            CTRL --> UI : requestedPublishedPropertiesList
            deactivate CTRL

            UI --> uUser : displays the respective list of properties
            deactivate UI


@enduml