@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Unregistered User" as uUser
participant ":ListPropertiesUI" as UI
participant ":ListPropertiesController" as CTRL
participant ":Repositories" as REPOS
participant "repositories\n:Repositories" as repos
participant "publishedPropertiesRepository:\nPublishedPropertiesRepository" as PublishedPropertiesRepository

activate uUser





'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            uUser -> UI : asks to list properties
            activate UI

            UI --> uUser : shows property filter and sort options
            deactivate UI


            alt Filter and Sort
                uUser -> UI : selects filters and asks to list properties (type of business, type of property, number of rooms)
                activate UI

                UI -> CTRL** : create

                UI -> CTRL : getPublishedPropertiesByFilter(propertyType, buisnessType, numberOfRooms)
                activate CTRL

                CTRL -> REPOS : getInstance()
                activate REPOS

                REPOS --> CTRL: repositories
                deactivate REPOS

                CTRL -> repos : getPublishedPropertiesRepository()
                activate repos

                repos --> CTRL: publishedPropertiesRepository
                deactivate repos

                CTRL -> PublishedPropertiesRepository : getPublishedPropertiesByFilter(propertType, buisnessType)
                activate PublishedPropertiesRepository

                PublishedPropertiesRepository --> CTRL : filteredPublishedPropertiesList
                deactivate PublishedPropertiesRepository

                CTRL --> UI : filteredPublishedPropertiesList
                deactivate CTRL

                UI --> uUser : shows filtered properties
                deactivate UI

                uUser -> UI : selects criteria to sort and asks to list properties (price, state)
                activate UI

                UI -> CTRL : getPublishedPropertiesBySort(price, state)
                activate CTRL

                repos --> CTRL : publishedPropertiesRepository
                deactivate repos

                CTRL -> PublishedPropertiesRepository : getPublishedPropertiesRepositoryBySort(price, state)
                activate PublishedPropertiesRepository

                PublishedPropertiesRepository --> CTRL : filteredAndSortedPublishedPropertiesList
                deactivate PublishedPropertiesRepository
            end

deactivate uUser

@enduml