@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right directio
class Property{
    - String location
    - double area
    - double price
    - double distanceFromCenter
    - PHOTOS???
}

class PublishedProperty {
    - Property typeOfProperty
    - String typeOfBusiness
    - String publishedDate
    - Agent publishedBy
    - double comission
}

class PublishedPropertiesRepository {
    - List<PublishedProperty> publishedProperties
    + getPublishedPropertiesByFilter()
    + getPublishedProperties()
    + sortProperties()
}


class Repositories {
    - PublishedPropertiesRepository publishedPropertiesRepository
    + Repositories()
    + getInstance() : Repositories
    + getPublishedPropertiesRepository()
}

class ListPropertiesController {
    - PublishedPropertiesRepository publishedPropertiesRepository
    + ListPropertiesController()
    + ListPropertiesController(publishedPropertiesRepository)
    + getPublishedPropertiesRepository()
}

class ListPropertiesUI {
}

Repositories -> Repositories : instances

ListPropertiesUI .> ListPropertiesController

ListPropertiesController ..> Repositories

Repositories "1" --> "1" PublishedPropertiesRepository : has

ListPropertiesController ..> PublishedPropertiesRepository

PublishedPropertiesRepository "1" --> "*" PublishedProperty : has


@enduml