@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Owner" as Owner
participant ":System" as System

activate Owner

        Owner -> System : ask to create Sale or Rent
    activate System

        System --> Owner : displays list of Agencies
    deactivate  System

        Owner -> System :submits selected Agency
    activate System

        System --> Owner :displays list of Agent
     deactivate System

        Owner -> System : submits selected Agent
     activate System

        System --> Owner : requests Owner data
    deactivate System

        Owner -> System : types requested data (name, citizen's card number, \ntax number, address, email address, \ncontact telephone number).
    activate System

        System --> Owner : requests type of transaction
    deactivate System


        Owner -> System : types requested data (Sale or Rent)
    activate System


    opt Rent

        System --> Owner: request contract duration
        deactivate System

        Owner -> System: types requested data
        activate System
    end

        System --> Owner : requests type of property
    deactivate System

        Owner -> System : types requested data (Apartement, House, Land)
    activate System

            System --> Owner : requests data of property
    deactivate System

    alt  Land

        Owner -> System: Select requested data (area (in m2), location, \ndistance from the city centre, requested price (USD), \nphotographs)
    activate System
    else  Apartement
        Owner -> System: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning).
    else  House
        Owner -> System: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning, \nexistence of a basement, existence of an inhabitable loft, sun exposure value.
    end

            System --> Owner : ask to confirm data
    deactivate System

            Owner -> System: confirm entered data
    activate System

        System --> Owner : displays operation success
    deactivate System


@enduml