@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true

skinparam rectangle{
    BorderColor yellow
}

title Use Case Diagram

left to right direction

rectangle "System Actors" as actors {
    actor "Unregistered User"
    actor "Organization Agent"
    actor "System Administrator"
    actor "Owner"
}


rectangle "Use Cases" as usecases{
    usecase "UC1 - Display listed properties" as UC1
            "Unregistered User" ---> UC1
    usecase "UC2 - Publish any sale announcement on the system" as UC2
            "Organization Agent" --> UC2
    usecase "UC3 - Register a new employee" as UC3
            "System Administrator" --> UC3
    usecase "UC4 - Submit Sale or Rent" as UC4
            "Owner" --> UC4
    usecase "UC7 - Register in the system to buy, sell or rent properties" as UC7
            "Unregistered User" --> UC7
}

@enduml