@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class Agency{
ID
name
email
phoneNumber
}

class Order{
    id
    announcementId
    orderAmount
    clientEmail
    date
    orderState
}

class LegacySystem{
}

class SystemAdministrator{
}

class Employee extends Person{
}

class Person{
        name
        email
        passportCardNumber
        taxNumber
        telephoneNumber
}

SystemAdministrator "1" -- "1" LegacySystem : imports information from >
SystemAdministrator "1" -- "1" Employee : creates from imported data >
SystemAdministrator "1" -- "1" Agency : creates from imported data >
SystemAdministrator "1" -- "1" Order : creates from imported data >

@enduml