@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true
skinparam linetype ortho


skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class User{
    name
    citizenCardNumber
    taxNumber
    address
    email
    contactTelephone
}

class SystemAdministrator {
   userName
   password
}

SystemAdministrator "1" --- "*" User : registers >


@enduml
