@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right directio
class Property{
      - area : double
      - distanceFromCenter : double
      - price : double
      - address : Address
      + getAddress() : Address
      + getArea() : double
      + getDistanceFromCenter() : int
      + getPrice() : double
      + toString() : String
}

class Announcement {
   - typeOfProperty : TypeOfProperty
   - transactionType : TransactionType
   - publishDate : Date
   - comission : Commission
   - photos ArrayList<Photo>
   - isPublished : boolean
   - id : int
   - idCounter : int
   + getProperty() : Property
   + toString() : String
}

class AnnouncementRepository {
    +getAllAnnouncementsSortedByDefualtCriteria() : ArrayList<Announcement>
    +getAllAnnouncementsSortedBySortCriteria(String sortCriteria, String order) : ArrayList<Announcement>
    +getFilteredAnnouncements(TypeOfProperty typeOfProperty, TransactionType transactionType, int numberOfRooms) : ArrayList<Announcement>
    +getFilteredAndSortedAnnouncements(TypeOfProperty typeOfProperty, TransactionType transactionType,\n int numberOfRooms, String sortCriteria, String order) : ArrayList<Announcement>
}

class Repositories {
    +Repositories()
    +getInstance() : Repositories
    +getAnnouncementRepository() : AnnouncementRepository
}

class ListAnnouncementsController {
     +getAnnoucementRepository() : Repository
     +getAllAnnouncementsSortedByDefualtCriteria() : ArrayList<Announcement>
     +getAllAnnouncementsSortedBySortCriteria(String sortCriteria, String order) : ArrayList<Announcement>
     +getFilteredAnnouncements(ypeOfProperty typeOfProperty, TransactionType transactionType, int numberOfRooms) : ArrayList<Announcement>
     +getFilteredAndSortedAnnouncements(TypeOfProperty typeOfProperty, TransactionType transactionType,\n int numberOfRooms, String sortCriteria, String order) : ArrayList<Announcement>
}

class ListAnouncementsUI {
    +checkInputType(typeOfProperty, transactionType, numberOfRooms, sortCriteria) : AnnouncementListOptionType
    +getAnnouncements(TypeOfProperty typeOfProperty, TransactionType transactionType,\n int numberOfRooms, String sortCriteria, String order) : ArrayList<Announcement>
    +getController() : ListAnnouncementsController
}

class Address{
    - street : String
    - city : String
    - district : String
    - state : String
    - zipCode : int
}

Repositories -> Repositories : instances

ListAnouncementsUI .> ListAnnouncementsController

ListAnnouncementsController ..> Repositories

Repositories "1" --> "1" AnnouncementRepository : has

ListAnnouncementsController ..> AnnouncementRepository

AnnouncementRepository "1" --> "*" Announcement : has

Announcement "1" --> "1" Property : has

Property "1" --> "1" Address : has


@enduml