@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true
'skinparam linetype ortho
skinparam classAttributeIconSize 0
'skinparam groupInheritance 2
'skinparam linetype polyline

'hide attributes
hide circle
hide methods
'left to right direction
title Domain Model

class StoreNetworkManager{
    name
    agencies
}

class SystemAdministrator{
   userName
   password
}

class StoreManager{
    name
    agency
}

class Property{
    typeOfBusiness
    typeOfProperty
    area
    location
    distanceFromCenter
    price
}

class Agent{
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class Agency{
    agents
    storeManager
}

class Buyer{
}

class Seller{
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber

}

class UnregisteredUser{
}

class PublishedProperty{
}

SystemAdministrator "1" -----> "*" Agent : creates
SystemAdministrator "1" -----> "*" Agency : creates
Buyer "*" -----> "*" Agent : contacts for purchase
Buyer "*" -----> "*" PublishedProperty : views
Seller "*" -----> "*" Agent : contacts for sale
StoreNetworkManager "1" -----> "*" Agency : manages
Agency "1" -----> "1" StoreManager  : managed by
Agent "*" -----> "*" PublishedProperty : publishes
Agency "1" -> "*" Agent : has
Seller "*" --> "*" Property : owns
UnregisteredUser "*" -----> "*" PublishedProperty : views

'SystemAdministrator "1" -right "*" Employee : registers
'PropertyOwner "1" --> "*" PropertyOrder : requests advertisement
'PropertyOwner "1" --> "1" Agent : contacts
'Agent "1" ----> "*" PropertyOrder : reviews
'Agent "1" -----> "*" Property : publishes
'UnregisteredUser "1" ---> "*" Property: can list

'Client <|---- RegisteredUser
'Client <|--- UnregisteredUser
'Client <|---- PropertyOwner
'User <|-- Client
'User <|-- Employee
'Employee <|-- Agent
'Employee <|----- StoreManager
'Employee <|----- StoreNetworkManager
'Property <|-- House
'Property <|-- Apartment
'Property <|-- Land
'Employee <|-- SystemAdministrator


@enduml