@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
skinparam groupInheritance 2
hide circle
hide methods

title Domain Model

class Client{
}

class User{
}

class RegisteredUser{
}

class UnregisteredUser{
}

class PropertyOwner{
}

class Employee{
}

class Agent{
}

class StoreManager{
}

class StoreNetworkManager{
}

class SystemAdministrator{
}

class PropertyOrder{
}

class Property{
}

class Apartment{
}

class House{
}

class Land{
}


SystemAdministrator "1" --> "*" Employee : registers
PropertyOwner "1" --> "*" PropertyOrder : requests advertisement
Agent "1" --> "*" PropertyOrder : reviews
Agent "1" --> "*" Property : publishes
UnregisteredUser "1" ---> "*" Property: can list

Client <|-- RegisteredUser
Client <|-- UnregisteredUser
Client <|-- PropertyOwner
User <|-- Client
User <|-- Employee
Employee <|-- Agent
Employee <|-- StoreManager
Employee <|-- StoreNetworkManager
Property <|-- House
Property <|-- Apartment
Property <|-- Land

@enduml