@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam groupInheritance 2
'skinparam linetype polyline

hide circle
hide methods
'left to right direction
title Domain Model

class Client{
}

class User{
}

class RegisteredUser{
}

class UnregisteredUser{
}

class PropertyOwner{
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class Employee{
    name
    citizenCardNumber
    taxNumber
    address
    email
    contactTelephone
    agency
}

class Agent{
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class StoreManager{
}

class StoreNetworkManager{
}

class SystemAdministrator{
   userName
   password
}

class PropertyOrder{
}

class Property{
    typeOfBusiness
    typeOfProperty
    area
    location
    distanceFromCenter
    price
}

class Apartment{
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces
    availableEquipment
}

class House{
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces
    availableEquipment
    basement
    inhabitableLoft
    sunExposure
}

class Land{
}


SystemAdministrator "1" -left "*" Employee : registers
PropertyOwner "1" --> "*" PropertyOrder : requests advertisement
PropertyOwner "1" --> "1" Agent : contacts
Agent "1" ----> "*" PropertyOrder : reviews
Agent "1" -----> "*" Property : publishes
UnregisteredUser "1" ---> "*" Property: can list

Client <|---- RegisteredUser
Client <|--- UnregisteredUser
Client <|---- PropertyOwner
User <|-- Client
User <|-- Employee
Employee <|-- Agent
Employee <|----- StoreManager
Employee <|----- StoreNetworkManager
Property <|-- House
Property <|-- Apartment
Property <|-- Land
Employee <|-- SystemAdministrator


@enduml