@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US003: Register New Employee

autonumber

actor "System Administrator" as Admin
participant ":System" as System

activate Admin

    Admin -> System : requests to register a new employee
    activate System

        System --> Admin : requests the role of the new employee
    deactivate System

    Admin -> System : provide the role of the new employee
        activate System

            System --> Admin : requests the name, the passport card number, the tax number, the address, \nthe email address, the contact telephone number

        deactivate System

    Admin -> System : provide the necessary data
        activate System

            System --> Admin : list the agencies
        deactivate System

    Admin -> System : select the agency from the list
    activate System

        System --> Admin : shows the provided data to confirm
    deactivate System

    Admin -> System : confirm the provided data
    activate System

        System --> Admin : validate the data and display success message
        System --> Admin : send the password to the employee's email

    deactivate System

@enduml
