@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class NetworkManager extends Employee{

}


class Deal{

}
class Property{
    area
    distanceFromCenter
    price
}

NetworkManager "1" -- "*" Deal : sort >
Deal "*" -- "1" Agency : belongs to >
Deal "1" -- "1" Property : have >

@enduml