@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US002 - Publish a Sale

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

Agent -> System : asks to create a new sale for publish from existing order
activate System

System --> Agent : Lists Announcements assigned to Agent that are not published yet\nand asks to select one
deactivate System

Agent -> System : selects an Announcement by its ID
activate System

System --> Agent : asks to set a Commission, either through a fixed amount or percentage
deactivate System

Agent -> System : selects the type of Commission
activate System

alt Fixed Amount
    System --> Agent : asks to type the Fixed Amount
    deactivate System

    Agent -> System : types the Fixed Amount
    activate System
else Percentage
    System --> Agent : asks to type the Percentage value
    deactivate System

    Agent -> System : types the Percentage value
    activate System
end

System --> Agent : validates Commission and sets it to the selected Announcement
deactivate System

Agent -> System : confirms the Published Announcement
activate System

System --> Agent : publishes the Announcement, sets the Published Date and shows operation success
deactivate System


@enduml