@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Owner" as Owner
participant ":System" as System

activate Owner

        Owner -> System : displays list of Agencies
    activate System

        System --> Owner :submits selected Agency
    deactivate System

        Owner -> System :displays list of Agent
     activate System

        System --> Owner: submits selected Agent
     deactivate System

        Owner -> System : Submit a request for listing a property for sale or rent
    activate System

        System --> Owner : requests Owner data
    deactivate System

        Owner -> System : types requested data (name, citizen's card number, \ntax number, address, email address, \ncontact telephone number).
    activate System

        System --> Owner : requests type of request
    deactivate System


        Owner -> System : types requested data (Sale or Rent)
    activate System


    alt if Rent

        System -> Owner: request contract duration
        deactivate System
    else
        Owner -> System: types requested data
        activate System
    end

        System --> Owner : requests type of property
    deactivate System

        Owner -> System : types requested data (Apartement, House, Land)
    activate System

            System --> Owner : requests data of property
    deactivate System

    alt if Land

        Owner -> System: Select requested data (area (in m2), location, \ndistance from the city centre, requested price (USD), \nphotographs)
    activate System
    else if Apartement
        Owner -> System: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning).
    else if House
        Owner -> System: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning, \nexistence of a basement, existence of an inhabitable loft, sun exposure value.
    end

        System --> Owner : displays operation success
    deactivate System


@enduml