@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Owner {
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class Agent {
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class Property{
    typeOfProperty
    area
    location
    distanceFromCityCentre
    requestedPrice
    photographs
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces
    availableEquipment
    hasBasement
    hasInhabitableLoft
    sunExposureValue
}

Owner "1" -- "1" Agent : calls
Agent "1" - "0..*" Property: creates
@enduml
