@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
'skinparam linetype ortho
hide circle
hide methods

title Domain Model

class Client extends User{
}

class Owner extends User {
}

class Employee extends User{
}

class Agent extends Employee{
}

class User{
    name
    passportCardNumber
    taxNumber
    email
    telephoneNumber
}

class Agency{
    ID
    name
    emailAddress
    phoneNumber
}

class Property{
    area
    distanceFromCenter
    price
}

class Photos {
}

class Address{
    doorNumber
    zipCode
}

class Street{
}

class City{
}

class District{
}

class State{
}

class Apartment extends Residency{
}

class House extends Residency{
    basement
    inhabitableLoft
}

class Residency extends Property{
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces

}

class Announcement{
    publishedDate
    publishedBy
    isPublished
}

class Commission{
    percentage
    value
}

class TypeOfProperty{
    APARTMENT
    HOUSE
    LAND
}

class Land extends Property{
}

class Equipment{
    equipmentName
}

class Role{
ADMIN
EMPLOYEE
CLIENT
STORE_NETWORK_MANAGER
STORE_MANAGER
}

class SystemAdministrator extends Employee{
}

class StoreManager extends Employee{
}

class StoreNetworkManager extends Employee{
}

class SunExposure{
NORTH
SOUTH
EAST
WEST
}

class TransactionType{
RENT
SALE
BUY
}

class UnregisteredUser{
}

'class Request{
'}

Agent "1" -- "1" Announcement: publishes >
Announcement "1" -- "1" TypeOfProperty: has a >
StoreNetworkManager "1" -- "*" StoreManager: manages >
Agency "1" -- "*" Agent: has >
SystemAdministrator "1" -- "*" Employee: creates >
Role "1" -- "1" User: has <
Agent "1" -- "1" Owner : contacted by >
'Agent "*" - "*" Property: publishes >
Agent "1" - "*" Property: sets commission >
Owner "1" -- "*" Property: owns >
Owner "1" - "*" Announcement: makes >
Announcement "*" -- "1" Agent: is requested to >
Announcement "1" - "1" Property: has >
Announcement "1" - "1" TransactionType: has >
Address "1" -- "1" State : part of <
City "*" -- "1" District : part of >
Street "*" -- "1" City : part of >
District "*" --- "1" State : part of >
Client "1" -- "*" Address: has an >
Announcement "1" -- "1..*" Photos: has >
Announcement "1" -- "1" Commission: is set for <
Residency "1" -- "*" Equipment: has >
Announcement "1" -- "1" Property: part of <
User "1" -- "*" Address: has >
Property "1" - "1" Address: has an >
Announcement "1" -- "1" Commission : has a >
StoreManager "1" -- "1" Agency: manages an >
House "1" -- "1" SunExposure: has a value of >
Announcement "1" -- "1" TransactionType: has a value of >
Agency "1" -- "1" Address: has an >
UnregisteredUser "1" -- "*" Announcement: views >


@enduml
