@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Owner" as ADM
participant ":CreateRequestUI" as UI
participant ":CreateRequestController" as CTRL
participant ":Repositories" as RepositorySingleton
'participant "repositories\n:Repositories" as PLAT
'participant "taskCategoryRepository:\nTaskCategoryRepository" as TaskCategoryRepository
'participant ":ApplicationSession" as _APP
'participant "appSession\n:ApplicationSession" as APP
'participant "currentSession\n:UserSession" as SESSAO
'participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
'participant "organization\n:Organization" as ORG
'participant "task\n:Task" as TAREFA

activate ADM

        ADM -> UI : ask to create Sale or Rent

        activate UI

            UI -> CTRL** : create Request
                UI --> : getAgencyList()
                UI --> UI :

                    UI --> ADM : displays list of Agencies

                deactivate  UI

                    ADM -> UI :submits selected Agency

                activate UI

                    UI --> : getAgentList()

                    UI --> ADM :displays list of Agent
                 deactivate UI

                    ADM -> UI : submits selected Agent

                 activate UI
                    UI --> : getOwnerListCharactristics()
                    UI --> ADM : requests ADM data
                deactivate UI

                    ADM -> UI : types requested data (name, citizen's card number, \ntax number, address, email address, \ncontact telephone number).

                activate UI
                    UI --> UI : Keep data (name, citizen's card number, \ntax number, address, email address, \ncontact telephone number)
                    UI --> : getTransactionType()
                    UI --> ADM : requests type of transaction

                    deactivate UI
                    ADM -> UI : types requested data (Sale or Rent)
                activate UI


                opt Rent
                    UI --> : getContractDuration()
                    UI --> ADM: request contract duration
                    deactivate UI

                    ADM -> UI: types requested data
                    activate UI
                end
                    UI --> : getPropertyTypeList()
                    UI --> ADM : requests type of property
                deactivate UI

                    ADM -> UI : types requested data (Apartement, House, Land)
                activate UI

                        UI --> : getPropertyListCharactristics()
                        UI --> ADM : requests data of property
                deactivate UI

                alt  Land

                    ADM -> UI: Select requested data (area (in m2), location, \ndistance from the city centre, requested price (USD), \nphotographs)
                activate UI
                else  Apartement
                    ADM -> UI: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning).
                else  House
                    ADM -> UI: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning, \nexistence of a basement, existence of an inhabitable loft, sun exposure value.
                end

                        UI --> ADM : ask to confirm data
                deactivate UI

                        ADM -> UI: confirm entered data
                activate UI

                    UI --> ADM : displays operation success
                deactivate UI


            @enduml