@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Owner" as ADM
participant ":CreateRequestUI" as UI
participant ":CreateRequestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "RequestListRepository:\nRequestListRepository" as RequestListRepository
participant "AgencyListRepository:\nAgencyListRepository" as AgencyListRepository
participant "AgentListRepository:\nAgentListRepository" as AgentListRepository
'participant "OwnerListRepository:\nOwnerListRepository" as OwnerListRepository
participant "request\n:Request" as REQUEST


activate ADM

        ADM -> UI : ask to create Sale or Rent

        activate UI

            UI -> CTRL** : create Request
                UI --> CTRL : getAgencyList()
                activate CTRL

                 CTRL -> RepositorySingleton : getInstance()

                 activate RepositorySingleton

                 RepositorySingleton --> CTRL: repositories

                 deactivate RepositorySingleton

                  CTRL -> PLAT : getAgencyListRepository()
                  activate PLAT

                  PLAT --> CTRL: AgencyListRepository
                  deactivate PLAT

                CTRL --> AgencyListRepository : getAgencyList()

                activate AgencyListRepository

                AgencyListRepository --> CTRL : AgencyList

                deactivate AgencyListRepository
                CTRL--> UI : AgencyList
                deactivate

                UI --> ADM : displays list of Agencies

                deactivate  UI

                    ADM -> UI :submits selected Agency

                activate UI
                UI --> UI : Keep data Agency
                UI --> CTRL : getAgentList()
                activate CTRL

                 CTRL -> RepositorySingleton : getInstance()

                 activate RepositorySingleton

                 RepositorySingleton --> CTRL: repositories

                 deactivate RepositorySingleton

                 CTRL -> PLAT : getAgentListRepository()
                 activate PLAT

                 PLAT --> CTRL: AgentListRepository
                 deactivate PLAT



                CTRL --> AgentListRepository : getAgentList()
                activate AgentListRepository

                AgentListRepository --> CTRL : AgentList
                deactivate AgentListRepository
                CTRL--> UI : AgentList
                deactivate CTRL

                UI --> ADM :displays list of Agent
                deactivate UI


                ADM -> UI : submits selected Agent
                activate UI
                UI --> UI : Keep data Agent


                'UI --> : getOwnerListCharactristics()

                UI --> ADM : requests ADM data
                deactivate UI

                    ADM -> UI : types requested data (name, citizen's card number, \ntax number, address, email address, \ncontact telephone number).

                activate UI

                    UI --> UI : Keep data (name, citizen's card number, \ntax number, address, email address, \ncontact telephone number)
                    'UI --> : getTransactionType()
                    UI --> ADM : requests type of transaction

                    deactivate UI
                    ADM -> UI : types requested data (Sale or Rent)

                activate UI
                    UI --> UI : Keep data TransactionType

                opt Rent
                 '   UI --> : getContractDuration()
                    UI --> ADM: request contract duration
                    deactivate UI

                    ADM -> UI: types requested data
                    activate UI
                    UI --> UI : Keep data contract
                end
                    'UI --> : getPropertyTypeList()
                    UI --> ADM : requests type of property
                deactivate UI

                    ADM -> UI : types requested data (Apartement, House, Land)
                activate UI

                       UI --> UI : Keep data type of property
                        UI --> ADM : requests data of property
                deactivate UI

                alt  Land

                    ADM -> UI: Select requested data (area (in m2), location, \ndistance from the city centre, requested price (USD), \nphotographs)
                activate UI
                else  Apartement
                    ADM -> UI: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning).
                else  House
                    ADM -> UI: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning, \nexistence of a basement, existence of an inhabitable loft, sun exposure value.
                end
                UI --> UI : Keep data of property

                        UI --> ADM : ask to confirm data
                deactivate UI

                        ADM -> UI: confirm entered data
                activate UI
                UI -> CTRL : create Request with all data
                activate CTRL
                CTRL -> RepositorySingleton : getInstance()

                 activate RepositorySingleton

                 RepositorySingleton --> CTRL: repositories

                 deactivate RepositorySingleton

                 CTRL -> RequestListRepository : getRequestListRepository()
                 activate RequestListRepository

                 RequestListRepository --> CTRL : RequestListRepository
                 CTRL -> RequestListRepository : create Request with all data

                 RequestListRepository -> REQUEST**: create Request with all data
                 RequestListRepository --> CTRL : request

                 deactivate RequestListRepository

                 CTRL --> UI :request
                 deactivate CTRL

                    UI --> ADM : displays operation success
                deactivate UI


            @enduml