
@startuml

'skinparam monochrome true

skinparam packageStyle rectangle

skinparam shadowing false

skinparam linetype polyline

'skinparam linetype orto




skinparam classAttributeIconSize 0


class Announcement {
+setIsPublished(): void
+toString(): String
}

enum TransactionType {
    RENT
    SALE
}

class AnnouncementRepository {
+addAnnouncementFromOwner: void

}

class AgencyListRepository{
+getAgencyList(id) : ArrayList<Agencies>

}

class EmployeeRepository{
+getEmployeeList(Agency) : ArrayList<Employee>
}




class Repositories {
+getInstance(): Repositories
+AgencyListRepository()
+getAnnouncementRepository()
+getEmployeeListRepository()
}




class CreateRequestController {
+CreateRequestController(AnnouncementRepository,\nAgencyListRepository,EmployeeRepository)
+getAgencyList()
+getEmployeeList()
+Createannouncemnt (Employee agent, TransactionType,\n TypeOfProperty,Property)
-getEmployeeList(Agency) : ArrayList<Employee>
-getAgencyListRepository() :
-getAnnouncementRepository()
}




class CreateRequestUI {
}

class Property{
    - double area
    - double distanceFromCenter
    - double price
    - Address address
    + getAddress()
    + getArea()
    + getDistanceFromCenter()
    + getPrice()
    + toString()
}
class Announcement {
    - TypeOfProperty typeOfProperty
    - TransactionType transactionType
    - Date publishDate
    - Comission comission
    - ArrayList<Photo> photos
    - boolean isPublished
    - int id
    - int idCounter
    + getProperty()
    + toString()
}
class Residence {
-int numberOfBedrooms
-int numberOfBathrooms
-int numberOfParkingSpaces
-boolean hasCentralHeating
-boolean hasAirConditioning
}

enum sunExposure{
NORTH
SOUTH
EAST
WEST
}
class Land {
}
class Apartment {
}
class House {
-boolean hasBasement
-boolean hasInhabitableLoft,
}

class Agency{
- int id
- String name
- String emailAddress
- int phoneNumber
- Address address
}

class Employee{
- int id
- String name
- String emailAddress
- int phoneNumber
- Address address
-
}

enum Role{
ADMIN
AGENT
STORE_NETWORK_MANAGER
STORE_MANAGER
CLIENT
}

class User{
}


CreateRequestUI .> CreateRequestController

CreateRequestController ..> Repositories
Repositories --> Repositories : instances
Repositories "1" --> "1" AgencyListRepository : has
Repositories "1" --> "1" AnnouncementRepository : has
Repositories "1" --> "1" EmployeeRepository : has

CreateRequestController ..> AnnouncementRepository : AnnouncementRepository
CreateRequestController ..> AgencyListRepository : AgencyListRepository
CreateRequestController ..> EmployeeRepository : EmployeeRepository

AnnouncementRepository "1" --> "*" Announcement : has

Announcement "1" --> "1" Property : has
Announcement "1" --> "1" TransactionType : has

Property "1" --> "1" Residence : has
Property "1" --> "1" Land : has
Residence  "1" --> "1" Apartment : has
Residence  "1" --> "1" House : has
House "1" --> "1" sunExposure

AgencyListRepository "1" --> "*" Agency : has

EmployeeRepository "1" --> "*" Employee : has
Employee "1" --> "1" Role : has

Agency --> "*" Employee : employs

Property "*" --> "1" User : Created by
@enduml





