@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Owner" as OWNER
participant ":CreateRequestUI" as UI
participant ":CreateRequestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "AnnouncementRepository:\nAnnouncementRepository" as AnnouncementRepository
participant "AgencyListRepository:\nAgencyListRepository" as AgencyListRepository
participant "EmployeeRepository:\nEmployeeRepository" as EmployeeRepository
participant "request\n:Request" as REQUEST


activate OWNER

        OWNER -> UI : ask to create Sale or Rent

        activate UI

            UI -> CTRL** : create Request
                UI --> CTRL : getAgencyList()
                activate CTRL

                 CTRL -> RepositorySingleton : getInstance()

                 activate RepositorySingleton

                 RepositorySingleton --> CTRL: repositories

                 deactivate RepositorySingleton

                  CTRL -> PLAT : getAgencyListRepository()
                  activate PLAT

                  PLAT --> CTRL: AgencyListRepository
                  deactivate PLAT

                CTRL --> AgencyListRepository : getAgencyList()

                activate AgencyListRepository

                AgencyListRepository --> CTRL : AgencyList

                deactivate AgencyListRepository
                CTRL--> UI : AgencyList
                deactivate

                UI --> OWNER : displays list of Agencies

                deactivate  UI

                    OWNER -> UI :submits selected Agency

                activate UI
                UI --> UI : Keep data Agency
                UI --> CTRL : getEmployeeList()
                activate CTRL

                 CTRL -> RepositorySingleton : getInstance()

                 activate RepositorySingleton

                 RepositorySingleton --> CTRL: repositories

                 deactivate RepositorySingleton

                 CTRL -> PLAT : getEmployeeListRepository()
                 activate PLAT

                 PLAT --> CTRL: EmployeeRepository
                 deactivate PLAT



                CTRL --> EmployeeRepository : getEmployeeList()
                activate EmployeeRepository

                EmployeeRepository --> CTRL : EmployeeList
                deactivate EmployeeRepository
                CTRL--> UI : EmployeeList
                deactivate CTRL

                UI --> OWNER :displays list of Employees as Agents
                deactivate UI


                OWNER -> UI : submits selected Agent
                activate UI
                UI --> UI : Keep data Agent


                    UI --> OWNER : requests type of transaction

                    deactivate UI
                    OWNER -> UI : types requested data (Sale or Rent)

                activate UI
                    UI --> UI : Keep data TransactionType

                opt Rent
                 '   UI --> : getContractDuration()
                    UI --> OWNER: request contract duration
                    deactivate UI

                    OWNER -> UI: types requested data
                    activate UI
                    UI --> UI : Keep data contract
                end
                    'UI --> : getPropertyTypeList()
                    UI --> OWNER : requests type of property
                deactivate UI

                    OWNER -> UI : types requested data (Apartement, House, Land)
                activate UI

                       UI --> UI : Keep data type of property
                        UI --> OWNER : requests data of property
                deactivate UI

                alt  Land

                    OWNER -> UI: Select requested data (area (in m2), location, \ndistance from the city centre, requested price (USD), \nphotographs)
                activate UI
                else  Apartement
                    OWNER -> UI: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning).
                else  House
                    OWNER -> UI: Select requested data (area (in m2), location, distance from the city centre, \nrequested price (USD), photographs, number of bedrooms,\nnumber of bathrooms, number of parking spaces,\nany available equipment (such as central heating and/or air conditioning, \nexistence of a basement, existence of an inhabitable loft, sun exposure value.
                end
                UI --> UI : Keep data of property

                        UI --> OWNER : ask to confirm data
                deactivate UI

                        OWNER -> UI: confirm entered data
                activate UI
                UI -> CTRL : create Request with all data
                activate CTRL
                CTRL -> RepositorySingleton : getInstance()

                 activate RepositorySingleton

                 RepositorySingleton --> CTRL: repositories

                 deactivate RepositorySingleton

                 CTRL -> AnnouncementRepository : getAnnouncementRepository()
                 activate AnnouncementRepository

                 AnnouncementRepository --> CTRL : AnnouncementRepository
                 CTRL -> AnnouncementRepository: create Request with all data

                 AnnouncementRepository -> REQUEST**: create AnnouncementRequest with all data
                 AnnouncementRepository --> CTRL : request

                 CTRL --> UI :request
                 deactivate CTRL

                    UI --> OWNER : displays operation success
                deactivate UI


            @enduml