@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class Order{
    id
    announcementId
    orderAmount
    clientEmail
    date
    orderState
}
SystemAdministrator "1" -- "1" Order : creates from imported data >

@enduml