@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class NetworkManager {

}

class Agency{
    id
    noOfProperties
}

class Algorithm{
    name
}

'NetworkManager "1" -- Property : divides into two subsets >
Algorithm "1" -- "*" Agency : divides into two subsets >
NetworkManager "1" -- "1"Algorithm : uses >

@enduml