@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class NetworkManager {

}

class Agency{
    id
}

class Property{

}

NetworkManager "1" -- Property : divides into two subsets >

@enduml