@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 21

actor "System Administrator" as sysAdmin
participant ":RegisterEmployeeUI" as UI

activate UI

group Send Password by Email
    UI -> UI : sendPasswordByEmail(email, generatedPassword)
    activate UI

    UI --> sysAdmin : password sent to the employee's email
end

deactivate UI

deactivate sysAdmin

@enduml
