@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 10

actor "System Administrator" as sysAdmin
participant ":RegisterEmployeeUI" as UI
participant ":RegisterEmployeeController" as CTRL
participant ":EmployeeRepository" as EmployeeRepo

activate UI

group Register New Employee
    UI -> CTRL : registerEmployee(role, name, passportCardNumber, taxNumber, address, email, telephoneNumber, selectedAgency)
    activate CTRL

    CTRL -> EmployeeRepo : createEmployee(role, name, passportCardNumber, taxNumber, address, email, telephoneNumber, selectedAgency)
    activate EmployeeRepo

    EmployeeRepo -> EmployeeRepo : validateData()
    activate EmployeeRepo

    EmployeeRepo --> EmployeeRepo : validationResult
    deactivate EmployeeRepo

    EmployeeRepo -> EmployeeRepo : generatePassword()
    activate EmployeeRepo

    EmployeeRepo --> EmployeeRepo : generatedPassword
    deactivate EmployeeRepo

    EmployeeRepo -> EmployeeRepo : saveEmployee()
    activate EmployeeRepo

    EmployeeRepo --> CTRL : success
    deactivate EmployeeRepo
end

CTRL --> UI : success
deactivate CTRL

UI -> UI : displaySuccessMessage()
activate UI

UI --> sysAdmin : operation success message
deactivate UI

@enduml
