@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto



skinparam classAttributeIconSize 0

class Employee {
+setIsPublished(): void
+toString(): String
}

class Commission {
-value: float
-percentage: double
+getValue(): float
+getPercentage(): double
}


class EmployeeRepository {
-ArrayList<> Employee: List<Employee>
+removeNonPublishedAnnouncements(ArrayList<Announcement>: resultAnnouncements): void
+getAnnouncementsByAgent(String: agentEmail): ArrayList<Announcement>
+removePublishedAnnouncements(ArrayList<Announcement>: resultAnnouncements): void
+getAnnouncementById(int: id): Announcement
}



class AuthenticationRepository{
+getCurrentUserSession(): UserSession
}



class Repositories {
+getInstance(): Repositories
+getAuthenticationRepository(): AuthenticationRepository
+EmployeeRepository(): EmployeeRepository
}



class RegisterEmployeeController {
-EmployeeRepository: EmployeeRepository
-authenticationRepository: AuthenticationRepository
+publishAnnouncement(int: id): void
+getAnnouncementById(int: id): Announcement
+getAnnouncementsByUser(): List<Announcement>
+setCommission(int: id, Commission: commission): void
}



class RegisterEmployeeUI {
-controller: RegisterEmployeeController
+PublishAnnouncementUI(): void
+run(): void
+getAnnouncementByUser(): List<Announcement>
+chooseCommissionOrValue(int: id): void
}

Repositories -> Repositories : instances
RegisterEmployeeUI .> RegisterEmployeeController
RegisterEmployeeController ..> Repositories
Repositories "1" --> "1" AuthenticationRepository : has
Repositories "1" --> "1" EmployeeRepository : has
RegisterEmployeeController ..> EmployeeRepository
RegisterEmployeeController ..> AuthenticationRepository
EmployeeRepository "1" --> "*" Employee : has
Employee "1" --> "1" Commission : has

@enduml