@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Network Manager" as NetworkManager
participant ":System" as System

activate NetworkManager

    NetworkManager -> System : Ask to list all deals made
    activate System

    System --> NetworkManager : Request to select the sort type
    deactivate System

    NetworkManager -> System: selects sort type
    activate System

    System --> NetworkManager: Display the list of deals sorted by property area
    deactivate System


@enduml