@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Network Manager" as Manager
participant ":System" as System

activate Manager

    Manager -> System : accesses the menu to divide the stores
    activate System

    System --> Manager : displays the list of stores and the number of properties of each store
    deactivate System

    Manager -> System : selects the option to divide the stores into two subsets
    activate System

    System --> Manager : displays algorithm response
    deactivate System


@enduml