@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Owner extends Person {
}


class Agent {
}

class Person{
    name
    passportCardNumber
    taxNumber
    email
    telephoneNumber
}

class Agency{
    ID
    name
    emailAddress
    phoneNumber
}

class Property{
    area
    distanceFromCenter
    price
}

class Photos {
}

class Rent {
    contractDuration
}

class Address{
    street
    doorNumber
    zipCode
}

class City{
}

class District{
}

class State{
}

class Apartment extends Residency{
}

class House extends Residency{
    basement
    inhabitableLoft
}

class Residency extends Property{
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces

}

class Land extends Property{
}

class Equipment{
    equipmentName
}

class SunExposure{
}

class Request{
TransactionType
}

Agency "1" -- "*" Agent: has >
Agent "1" -- "1" Owner : contacted by >
Agent "*" - "*" Property: publishes >
Agent "1" - "*" Property: sets commission >
Owner "1" - "*" Property: owns >
Owner "1" - "1" Request: create >
Request "1" -- "1" Property: has an >
Request "1" -- "1" Agent: is sent to >
Request "1" - "1" Rent: has >
Address "1" -- "1" State : is part of <
City "*" -- "1" District : are part of >
District "*" -- "1" State : are part of >
Property "1" -- "*" Photos: has >
'House "1" -- "*" Equipment: has >
'Apartment "1" -- "*" Equipment: has >
Residency "1" -- "*" Equipment: has >
Person "1" -- "*" Address: has >
Property "1" - "1" Address: has an >
House "1" -- "1" SunExposure: has a value of >
Agency "1" -- "1" Address: has an >


@enduml
