@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram - US19

autonumber

actor "NetworkManager" as NetworkManager
participant "NetworkManagerDivideStoresWindow: UI" as UI
participant "StoreDivisionController: Controller" as Controller
participant "Property: Domain" as Property
participant "ImportController: Controller" as ImportController

activate NetworkManager

NetworkManager -> UI : asks to divide stores
activate UI

UI -> ImportController : readFile(filePath: String, delimiter: String)
activate ImportController

ImportController --> UI : dataToImport: ArrayList<String[]>
deactivate ImportController

UI -> ImportController : importData(dataToImport: ArrayList<String[]>)
activate ImportController
ImportController --> UI : importResult: String
deactivate ImportController

UI -> Controller : partitionTest2(properties: List<Property>)
activate Controller

Controller -> Controller: preparePropertyList(properties: List<Property>)
activate Controller
Controller -> Property: new Property(property.getAgencyID(), property.getNoOfProperties())
activate Property
Property --> Controller: Property
deactivate Property
Controller --> Controller: properties: List<Property>
deactivate Controller

Controller -> Controller: findBalancedPartition(properties: List<Property>)
activate Controller
loop "for each partition" as l1
Controller -> Controller: calculateDifferenceOfSums(partition: List<List<Property>>)
activate Controller
Controller -> Property: getNoOfProperties()
activate Property
Property --> Controller: noOfProperties: int
deactivate Property
Controller --> Controller: differenceOfSums: int
deactivate Controller
end
Controller --> Controller: bestPartition: List<List<Property>>
deactivate Controller

Controller -> Controller: calculateDifferenceOfSums(bestPartition: List<List<Property>>)
activate Controller
Controller -> Property: getNoOfProperties()
activate Property
Property --> Controller: noOfProperties: int
deactivate Property
Controller --> Controller: differenceOfSums: int
deactivate Controller

Controller --> UI: result: Map<String, Object>
deactivate Controller

UI --> NetworkManager : displays result
deactivate UI

@enduml
