@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

title Class Diagram - US19

class StoreDivisionController {
    - Repositories
    - storeList: List<Store>
    - agencyList: List<Agency>
    - sumOfAllStores: double
    - sumOfEachAgency: List<Double>
    + prepareStoreList(): List<Store>
    + partitionTest2(): void
    + findBalancedPartition(): List<Agency>
    + calculateDifferenceOfSums(): double
    + getProperties(): void
}

class Property {
    - agencyID: int
}

class Agency {
    - id: int
    - noOfProperties: int
    - stores: List<Store>
}

class NetworkManagerDivideStoresWindow {
    - StoreDivisionController: StoreDivisionController
    - btnImport: Button
    - btnRunTimeTests: Button
    - btnDivideStores: Button
    - btReturn: Button
    + getProperties(): void
    + onBtReturn(): void
    + onBtImport(): void
    + onbtnRunTimeTests(): void
    + onBtnDivideStores(): void
}

class Store {
    - id: int
    - size: double
}

StoreDivisionController ..> Property
StoreDivisionController ..> Agency
StoreDivisionController ..> Store
NetworkManagerDivideStoresWindow ..> StoreDivisionController

@enduml
