@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram - US19


autonumber

actor "NetworkManager" as NetworkManager
participant "NetworkManagerDivideStoresWindow: UI" as UI
participant "StoreDivisionController: Controller" as Controller
participant "Agency: Domain" as Agency

activate NetworkManager

NetworkManager -> UI : asks to divide stores
activate UI

UI -> Controller: getInstance()
activate Controller

Controller --> UI : storeDivisionController
deactivate Controller

UI -> Controller : prepareStoreList(stores: List<Agency>)
activate Controller

Controller -> Agency: new Agency(agency.getId(), agency.getNoOfProperties())
activate Agency
Agency --> Controller: Agency
deactivate Agency

Controller --> UI: stores: List<Agency>
deactivate Controller

NetworkManager -> UI : confirms list
activate UI

UI -> Controller : partitionTest2(stores: List<Agency>)
activate Controller

Controller -> Controller: prepareStoreList(stores: List<Agency>)
activate Controller
Controller -> Agency: new Agency(agency.getId(), agency.getNoOfProperties())
activate Agency
Agency --> Controller: Agency
deactivate Agency
Controller --> Controller: stores: List<Agency>
deactivate Controller

Controller -> Controller: findBalancedPartition(stores: List<Agency>)
activate Controller
loop "for each partition" as l1
Controller -> Controller: calculateDifferenceOfSums(partition: List<List<Agency>>)
activate Controller
Controller -> Agency: getNoOfProperties()
activate Agency
Agency --> Controller: noOfProperties: int
deactivate Agency
Controller --> Controller: differenceOfSums: int
deactivate Controller
end
Controller --> Controller: bestPartition: List<List<Agency>>
deactivate Controller

Controller -> Controller: calculateDifferenceOfSums(bestPartition: List<List<Agency>>)
activate Controller
Controller -> Agency: getNoOfProperties()
activate Agency
Agency --> Controller: noOfProperties: int
deactivate Agency
Controller --> Controller: differenceOfSums: int
deactivate Controller

Controller --> UI: result: Map<String, Object>
deactivate Controller

UI --> NetworkManager : displays result
deactivate UI

@enduml
