@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) of US015 - List all booking requests for properties managed by the agent

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent


    Agent -> System : Ask to list all booking requests for properties
        activate System

        System --> Agent : Show all booking requests for properties managed by the agent
    deactivate System

@enduml