@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

skinparam classAttributeIconSize 0

title Class Diagram - US15

class UserSession {
    +getUserEmail()
}

abstract class Person{
    - name : String
    - email : String
}

class Employee extends Person{
}

class Announcement {
    - id : int
    - Property : property
    - Employee : agent
}

class VisitSchedule {
    - propertyID : int
    - visitDate : LocalDate
    - startTime : LocalTime
    - endTime : LocalTime
    - approvedByAgent : boolean
    - agentEmail : String
    - adressOfProperty : String
    - requesterEmail : String
}

class AuthenticationRepository {
    +doLogin()
    +doLogout()
    +getCurrentUserSession()
    +addUserRole()
    +addUserWithRole()
}

class AuthenticationController {
    - authController : AuthenticationController
    +getUserEmail()
}

class VisitScheduleRequestsWindow {
    +listPendingVisits()
    +showFilteredVisits()
    +onbtFilterSchedules()
    +onBtReturn()
    +getMainStage()
}

class VisitScheduleController {
    - visitScheduleRepository : VisitScheduleRepository
    - announcementRepository : AnnouncementRepository
    - clientRepository : ClientRepository
    - authController : AuthenticationController
    - employeeRepository : EmployeeRepository
    - emailSender : EmailSender
    +getPendingVisitsByAgentEmail()
    +getFilteredVisitsByAgentEmail()
    +getSortVisitScheduleFromConfig()
}

class Repositories {
    +getAnnouncementRepository()
    +getEmployeeRepository()
    +getVisitScheduleRepository()
}

class AnnouncementRepository {
    +getAnnouncement()
    +getAgentEmailFromAnnouncement()
    +getAllAnnouncementsSortedByDefaultCriteria()
}

class EmployeeRepository {
    +getEmployeeByEmail()
}

class VisitScheduleRepository {
    +getVisitSchedulesByUserEmailAndDate()
    +getVisitSchedulesByAgentAndPeriod()
    +addVisitSchedule()
    +sortVisitSchedules()
}

interface SortVisitSchedule {
    +sort()
}

class BubbleSortVisitSchedule implements SortVisitSchedule {
    +sort()
}

class QuickSortVisitSchedule implements SortVisitSchedule {
    +sort()
}

UserSession <.. AuthenticationRepository
AuthenticationController ..> AuthenticationRepository
VisitScheduleRequestsWindow ..> AuthenticationController
VisitScheduleRequestsWindow ..> VisitScheduleController
Repositories <.. VisitScheduleController
AnnouncementRepository <-- Repositories: has
EmployeeRepository <-- Repositories: has
VisitScheduleRepository <-- Repositories: has
SortVisitSchedule <.. VisitScheduleRepository
Announcement <-- AnnouncementRepository: has
Employee <-- EmployeeRepository: has
VisitSchedule <-- VisitScheduleRepository: has
Repositories --> Repositories : Instances

@enduml
