@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class Person {
    name
    passportCardNumber
    taxNumber
    email
    telephoneNumber
}

class Employee extends Person {
}

class SystemAdministrator extends Employee {
}

class Role {
}

class Address {
    street
    doorNumber
    zipCode
}

class City {
}

class District {
}

class State {
}

SystemAdministrator "1" -- "*" Employee: creates >
Employee "1" -- "1" Person: is an >
Employee "1" -- "1" Role: has a role of >
SystemAdministrator "1" -- "1" Role: has a >
Person "1" -- "*" Address: has >
Address "1" -- "1" City : is a part of a <
City "1" -- "1" District : is a part of a <
District "1" -- "1" State : is a part of a <

@enduml
