@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Network Manager" as NM
participant ":NetworkManagerSortWindow" as UI
participant ":PropertyOrderManagementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "PropertyDealRepository:\nPropertyRepository" as PropertyRepository
'participant "SortProperty" as SortProperty


activate NM

NM -> UI : Ask to list all deals made
activate UI

UI -> CTRL : getPropertiesDealSortByID()
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

 CTRL -> PLAT : getPropertyDealRepository()
activate PLAT

PLAT --> CTRL: getPropertyDealRepository
deactivate PLAT

CTRL --> PropertyRepository : getPropertiesDealSortByID()
activate PropertyRepository

 PropertyRepository --> CTRL : getPropertiesDealSortByID
deactivate PropertyRepository

CTRL--> UI : getPropertiesDealSortByID
deactivate

 UI -> NM: Display list of all properties with deal made\n sorted by ID
 deactivate



alt Selection Sort

 NM -> UI : Select Selection sort descending/ascending order
 activate UI
UI -> CTRL : getPropertiesDealSelectionSort()
activate CTRL

CTRL -> PropertyRepository : getPropertiesDealSelectionSort()
activate PropertyRepository

PropertyRepository --> CTRL : PropertiesDealSelectionSort
deactivate PropertyRepository

CTRL--> UI : PropertiesDealSelectionSort
deactivate

UI -> NM: Displays the list of all properties sorted by area \n using Selection algorithm
deactivate

else Insertion Sort

 NM -> UI : Select Insertion sort descending/ascending order
 activate UI
UI -> CTRL : getPropertiesDealInsertionSort()
activate CTRL

CTRL -> PropertyRepository : getPropertiesDealInsertionSort()
activate PropertyRepository

PropertyRepository --> CTRL : PropertiesDealInsertionSort
deactivate PropertyRepository

CTRL--> UI : PropertiesDealInsertionSort
deactivate

UI -> NM: Displays the list of all properties sorted by area \n using Insertion algorithm
deactivate

end
@enduml