@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Network Manager" as NM
participant ":NetworkManagerSortWindow" as UI
participant ":PropertyOrderManagementController" as CTRL
participant "ImportController" as ImportController
participant "CSVImport" as CSVImport
participant "repositories\n:Repositories" as PLAT
participant "PropertyDealRepository:\nPropertyRepository" as PropertyRepository

activate NM

NM -> UI : Ask to list all deals made
activate UI

UI -> NM : displays options import file
deactivate UI



    NM -> UI : Selects file to import
    activate UI

    UI -> ImportController : onBtImport
    activate ImportController

    ImportController -> CSVImport : importData()
    activate CSVImport

    CSVImport -> PLAT : getInstance()
    activate PLAT

    PLAT -> PropertyRepository: getPropertyDealRepository()
    activate PropertyRepository

    PropertyRepository -> PLAT : PropertyDealRepository
    deactivate PropertyRepository

    PLAT -> CSVImport : PropertyDealRepository
    deactivate PLAT

    CSVImport ->  PropertyRepository: importCSV()
    activate PropertyRepository

    PropertyRepository -> CSVImport: success
    deactivate PropertyRepository

    CSVImport -> ImportController : success
    deactivate CSVImport

    ImportController -> UI : success
    deactivate ImportController



UI -> CTRL : getPropertiesDealSortByID()
activate CTRL


CTRL --> PropertyRepository : getPropertiesDealSortByID()
activate PropertyRepository

 PropertyRepository --> CTRL : getPropertiesDealSortByID
deactivate PropertyRepository

CTRL--> UI : getPropertiesDealSortByID
deactivate

 UI -> NM: Display list of all properties with deal made\n sorted by ID
 deactivate



alt Selection Sort

 NM -> UI : Select Selection sort descending/ascending order
 activate UI
UI -> CTRL : getPropertiesDealSelectionSort()
activate CTRL

CTRL -> PropertyRepository : getPropertiesDealSelectionSort()
activate PropertyRepository

PropertyRepository --> CTRL : PropertiesDealSelectionSort
deactivate PropertyRepository

CTRL--> UI : PropertiesDealSelectionSort
deactivate

UI -> NM: Displays the list of all properties sorted by area \n using Selection algorithm
deactivate

else Insertion Sort

 NM -> UI : Select Insertion sort descending/ascending order
 activate UI
UI -> CTRL : getPropertiesDealInsertionSort()
activate CTRL

CTRL -> PropertyRepository : getPropertiesDealInsertionSort()
activate PropertyRepository

PropertyRepository --> CTRL : PropertiesDealInsertionSort
deactivate PropertyRepository

CTRL--> UI : PropertiesDealInsertionSort
deactivate

UI -> NM: Displays the list of all properties sorted by area \n using Insertion algorithm
deactivate

end
@enduml