@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Network Manager" as Admin
participant ":ImportUI" as UI
participant ":PropertyOrderManagementController" as CTRL
participant "repositories\n:Repositories" as Repositories
participant ":PropertyRepository" as PropertyRepository


    activate Admin

    Admin -> UI : Ask to list all deals made
    activate UI

    UI -> CTRL: getInstance()
    activate CTRL

'    CTRL -> UI : importController
'    activate REPO

'    UI -> CTRL : selectFile()
'    activate CTRL

    CTRL --> UI : selectFile()
    deactivate CTRL

    UI --> Admin : Request to select the sort type
    deactivate UI

    Admin -> UI : Selects sort type
    activate UI

    UI -> CTRL : checkFile()
    activate CTRL

    CTRL -> REPO : getInstance()
    activate REPO

    REPO --> CTRL: repositories
    deactivate REPO

    CTRL -> REPO : getAnnouncementRepository()
    activate REPO

    REPO -> ANNREPO : getAuthenticationRepository()
    activate ANNREPO

    ANNREPO --> REPO: authenticationRepository
    deactivate ANNREPO

    REPO --> CTRL: announcementRepository
    deactivate REPO

    CTRL --> ANNREPO: addAnnouncementFromImportedFile()
    activate ANNREPO

    ANNREPO -> CTRL : returns importResult
    deactivate ANNREPO

    CTRL -> UI : displayImportResult(importResult)
    deactivate CTRL

    UI --> Admin : Display the list of deals sorted by property area
    deactivate UI

@enduml
