@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Unregistered User" as User
participant ":System" as System

activate User

    User -> System : selects a property categories (type, number of rooms)
    activate System

        System --> User : lists properties
    deactivate System




@enduml